"""add new clomn telegram_message_id into message table

Revision ID: 99bab890f86e
Revises: 0d7523700261
Create Date: 2026-03-16 21:37:48.029375

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "99bab890f86e"
down_revision: Union[str, Sequence[str], None] = "0d7523700261"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "messages",
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
    )
    op.create_unique_constraint(None, "messages", ["telegram_message_id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="unique")
    op.drop_column("messages", "telegram_message_id")
